### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by voat** [IBM-Bluemix/iot-sensor-tag#3]
Hello,

I tried to run this demo on Windows but I get the following error:

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: noble
@0.3.9

Any way to get this running on windows?

**Comment by ryanjbaxter** [comment]
Can you paste the entire `npm install` output?  I do not have a Windows machine to try this on.

**Comment by joakimjnsson** [comment]
3355 verbose cwd C:\Users\Joakim\Desktop\iot sensor tag\publish
3356 error Windows_NT 6.3.9600
3357 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
3358 error node v0.12.0
3359 error npm  v2.5.1
3360 error code EBADPLATFORM
3361 error notsup Unsupported
3361 error notsup Not compatible with your operating system or architecture: noble@0.3.9
3361 error notsup Valid OS:    darwin,linux
3361 error notsup Valid Arch:  any
3361 error notsup Actual OS:   win32
3361 error notsup Actual Arch: ia32
3362 verbose exit [ 1, true ]
3363 verbose unbuild node_modules\sensortag
3364 info preuninstall sensortag@0.1.9
3365 info uninstall sensortag@0.1.9
3366 verbose unbuild rmStuff sensortag@0.1.9 from C:\Users\Joakim\Desktop\iot sensor tag\publish\node_modules
3367 info postuninstall sensortag@0.1.9
3368 verbose gentlyRm vacuuming C:\Users\Joakim\Desktop\iot sensor tag\publish\node_modules\sensortag
3369 silly gentlyRm purging C:\Users\Joakim\Desktop\iot sensor tag\publish\node_modules\sensortag
3370 silly gentlyRm quitting because other entries in C:\Users\Joakim\Desktop\iot sensor tag\publish\node_modules

--

Is this enough or do you want the full log?

**Comment by ryanjbaxter** [comment]
It looks like the noble library that the sensor tag library uses only works on unix based OSes.  Based on their [NPM page](https://www.npmjs.com/package/noble) Windows support is a future ToDo item.
